site_name: Formula

repo_name: 'Formula'
repo_url: 'https://github.com/instacart/formula'

theme:
  name: 'material'
  palette:
    primary: 'green'

extra_css:
  - 'css/app.css'


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - 'Overview': index.md
  - 'How It Works': how-it-works.md
  - 'Input': input.md
  - 'Output': output.md
  - 'State': state.md
  - 'Actions': actions.md
  - 'Composition': composition.md
  - 'Testing': testing.md
  - 'Performance': performance.md
  - 'Formula Android': Formula-Android.md
  - 'Using Android View Model': android-view-model.md
  - 'Advanced: Extending Action Interface': action-custom.md
  - 'Contributing': CONTRIBUTING.md
