enableFeaturePreview("VERSION_CATALOGS")

include(
    ":formula",
    ":formula-android",
    ":formula-android-compose",
    ":formula-android-tests",
    ":formula-lint",
    ":formula-rxjava3",
    ":formula-coroutines",
    ":formula-test",
)
include(
    ":samples:composition",
    ":samples:counter",
    ":samples:custom-network-state-stream",
    ":samples:stopwatch",
    ":samples:stopwatch-coroutines",
    ":samples:stopwatch-compose",
    ":samples:todoapp"
)
